fix "fatal: Need to specify how to reconcile divergent branches." (#5)
* fix "fatal: Need to specify how to reconcile divergent branches."

which would later failed the deployment because gha failed
to push the updated branch with

error: failed to push some refs to 'https://github.com/labforward/platform-deployment'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.

* update example instruction

checking out the project is not necessary